package com.arnav.music.domain.metadata

/**
 * Credits from a YouTube video description.
 *
 * Auto-generated "Topic" descriptions have a fixed shape:
 * ```
 * Provided to YouTube by <Label>
 *
 * <Title> · <Artist> · <Artist 2>
 *
 * <Album>
 *
 * ℗ 2019 <Owner>
 *
 * Released on: 2019-05-03
 *
 * Composer: X
 * Producer, Mixer: Y
 * Auto-generated by YouTube.
 * ```
 * Other descriptions are free-form; only "Role: Name" lines with a recognisable music role
 * ("Music: …", "Lyrics: …", "Singer: …", "Mixed & Mastered by: …") are used, so links, social
 * handles and film credits are left out.
 */
object DescriptionCredits {
    private val providedBy = Regex("""^provided to youtube by\s+(.+)$""", RegexOption.IGNORE_CASE)
    private val autoGenerated = Regex("""^auto-generated by youtube\.?$""", RegexOption.IGNORE_CASE)
    private val releasedOn = Regex("""^released\s+on\s*[:：]\s*(\d{4}(?:-\d{2}(?:-\d{2})?)?)""", RegexOption.IGNORE_CASE)
    private val phonographic = Regex("""^(?:℗|\(p\))\s*(.+)$""", RegexOption.IGNORE_CASE)
    private val copyright = Regex("""^(?:©|\(c\))\s*(.+)$""", RegexOption.IGNORE_CASE)
    private val roleLine = Regex("""^([^:：]{1,48}?)\s*[:：]\s*(.+)$""")
    /** "Music by A", "Lyrics by B" without a colon (free-form descriptions). */
    private val byLine = Regex("""^((?:music|lyrics|words|composed|written|produced|mixed|mastered|arranged|programmed|sung)(?:\s*(?:&|and|,)\s*\w+)*)\s+by\s+(.+)$""", RegexOption.IGNORE_CASE)
    private val ws = Regex("""\s+""")
    private val nameSplit = Regex("""\s*(?:,|&|;|\s+and\s+|\s+x\s+|\s/\s)\s*""", RegexOption.IGNORE_CASE)
    private val isrc = Regex("""^isrc\s*[:：]?\s*([A-Z]{2}-?[A-Z0-9]{3}-?\d{2}-?\d{5})$""", RegexOption.IGNORE_CASE)

    /** True for YouTube's auto-generated art-track descriptions. */
    fun isTopic(description: String): Boolean {
        val lines = description.lines().map { it.trim() }
        return lines.any { providedBy.matches(it) } || lines.any { autoGenerated.matches(it) }
    }

    fun parse(description: String): TrackCredits {
        if (description.isBlank()) return TrackCredits.Empty
        val lines = description.replace("\r\n", "\n").replace('\r', '\n').lines().map { it.replace(ws, " ").trim() }
        val topic = isTopic(description)
        val b = CreditsBuilder()
        var label: String? = null
        var album: String? = null
        var released: String? = null
        /** Title and album lines of a Topic description (never read as "Role: Name"). */
        val structural = HashSet<String>()

        if (topic) {
            // Paragraph structure: [provided by] [title · artists] [album] [℗] [released] [credits].
            val paragraphs = paragraphs(lines)
            val providedIndex = paragraphs.indexOfFirst { p -> p.any { providedBy.matches(it) } }
            paragraphs.getOrNull(providedIndex)?.firstNotNullOfOrNull { providedBy.matchEntire(it)?.groupValues?.get(1) }?.let { label = it }
            val titleIndex = paragraphs.indexOfFirst { p -> p.size == 1 && p[0].contains(" · ") }
            if (titleIndex >= 0) {
                structural += paragraphs[titleIndex][0]
                val parts = paragraphs[titleIndex][0].split(" · ").map { it.trim() }.filter { it.isNotEmpty() }
                parts.drop(1).forEachIndexed { i, a -> b.person(CreditGroup.PERFORMED, if (i == 0) "Artist" else "Featured artist", a) }
                val next = paragraphs.getOrNull(titleIndex + 1)
                if (next != null && next.size == 1 && isPlainText(next[0])) {
                    album = next[0]
                    structural += next[0]
                }
            }
        }

        for (line in lines) {
            if (line.isEmpty()) continue
            if (autoGenerated.matches(line)) continue
            if (line in structural) continue
            val provided = providedBy.matchEntire(line)
            if (provided != null) {
                if (label == null) label = provided.groupValues[1]
                continue
            }
            releasedOn.find(line)?.let { released = it.groupValues[1] }
            if (releasedOn.containsMatchIn(line)) continue
            phonographic.matchEntire(line)?.let { b.fact(CreditGroup.RIGHTS, "Recording copyright", "℗ " + it.groupValues[1].trim()) }
            if (phonographic.matches(line)) continue
            copyright.matchEntire(line)?.let { b.fact(CreditGroup.RIGHTS, "Copyright", "© " + it.groupValues[1].trim()) }
            if (copyright.matches(line)) continue
            isrc.matchEntire(line)?.let { b.fact(CreditGroup.IDENTIFIERS, "ISRC", it.groupValues[1].uppercase()) }
            if (isrc.matches(line)) continue

            val (role, value) = roleLine.matchEntire(line)?.let { it.groupValues[1].trim() to it.groupValues[2].trim() }
                ?: byLine.matchEntire(line)?.let { it.groupValues[1].trim() to it.groupValues[2].trim() }
                ?: continue
            if (value.isEmpty() || value.contains("://") || value.startsWith("www.", ignoreCase = true)) continue
            if (role.any { it.isDigit() } && !role.contains("3d", ignoreCase = true)) continue // timestamps, "Track 1"
            val lower = role.lowercase()
            when {
                lower == "album" || lower == "movie album" -> { if (album == null) album = value; continue }
                lower == "genre" -> { b.fact(CreditGroup.IDENTIFIERS, "Genre", value); continue }
                lower == "isrc" -> { b.fact(CreditGroup.IDENTIFIERS, "ISRC", value.uppercase()); continue }
                lower == "upc" -> { b.fact(CreditGroup.IDENTIFIERS, "UPC", value); continue }
            }
            val classified = CreditRoles.classify(role, lenient = topic)
            if (classified.isEmpty()) continue
            for (c in classified) {
                if (c.group == CreditGroup.RIGHTS) {
                    if (c.role == "Label" && label == null) label = value else b.fact(CreditGroup.RIGHTS, c.role, value)
                    continue
                }
                // Topic pages list one person per line; free-form lines often pack several names.
                val names = if (topic) listOf(value) else value.split(nameSplit)
                val maxWords = if (topic) 8 else 6
                names.filter { n -> n.split(' ').count { it.isNotEmpty() } <= maxWords }.forEach { n -> b.person(c.group, c.role, n) }
            }
        }

        label?.let { b.fact(CreditGroup.RIGHTS, "Label", it) }
        album?.let { b.fact(CreditGroup.IDENTIFIERS, "Album", it) }
        released?.let { b.fact(CreditGroup.IDENTIFIERS, "Released", it) }
        return order(b.build())
    }

    /** Label first within rights, so the page reads "Label · ℗ · ©". */
    private fun order(c: TrackCredits): TrackCredits {
        val rank = mapOf("Label" to 0, "Publisher" to 1, "Distributor" to 2, "Recording copyright" to 3, "Copyright" to 4)
        val rights = c.entries.filter { it.group == CreditGroup.RIGHTS }.sortedBy { rank[it.role] ?: 5 }
        val idRank = mapOf("Album" to 0, "Released" to 1, "Genre" to 2, "ISRC" to 3, "UPC" to 4)
        val ids = c.entries.filter { it.group == CreditGroup.IDENTIFIERS }.sortedBy { idRank[it.role] ?: 5 }
        return TrackCredits(c.entries.filter { it.group != CreditGroup.RIGHTS && it.group != CreditGroup.IDENTIFIERS } + rights + ids)
    }

    private fun isPlainText(s: String): Boolean =
        s.isNotBlank() && !s.contains(':') && !s.contains('：') && !phonographic.matches(s) && !copyright.matches(s) && !s.contains("://")

    private fun paragraphs(lines: List<String>): List<List<String>> {
        val out = ArrayList<List<String>>()
        var cur = ArrayList<String>()
        for (l in lines) {
            if (l.isEmpty()) {
                if (cur.isNotEmpty()) { out += cur; cur = ArrayList() }
            } else cur += l
        }
        if (cur.isNotEmpty()) out += cur
        return out
    }
}
